name: Sync on DOM Cloud
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"source":"clear","root":"public_html/public","features":["php
            latest","mysql"],"nginx":{"fastcgi":"on","locations":[{"match":"/","try_files":"$uri
            $uri/ /index.php$is_args$args"},{"match":"~
            \\.[^\\/]+(?<!\\.php)$","try_files":"$uri
            =404"}]},"commands":["composer create-project laravel/laravel .","cp
            .env.example .env","sed -ri \"s/(#
            )?DB_CONNECTION=.*/DB_CONNECTION=mysql/g\" .env","sed -ri \"s/(#
            )?DB_HOST=.*/DB_HOST=localhost/g\" .env","sed -ri \"s/(#
            )?DB_PORT=.*/DB_PORT=3306/g\" .env","sed -ri \"s/(#
            )?DB_DATABASE=.*/DB_DATABASE=${DATABASE}/g\" .env","sed -ri \"s/(#
            )?DB_USERNAME=.*/DB_USERNAME=${USERNAME}/g\" .env","sed -ri \"s/(#
            )?DB_PASSWORD=.*/DB_PASSWORD=${MYPASSWD}/g\" .env","sed -ri
            \"s/APP_URL=.*/APP_URL=https:\\/\\/${DOMAIN}/g\" .env","sed -ri
            \"s/LOG_STACK=single/LOG_STACK=daily,errorlog/g\" .env","php artisan
            migrate:fresh --seed","php artisan key:generate","php artisan
            storage:link","npm install","npm run build","chmod 0750 -R storage
            || true","echo \"opcache.revalidate_freq = 0\" >>
            public_html/.user.ini"],"wait":1}
          verbose: true
      - name: Check deployment status
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploycheck
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}